### ISSUE TITLE
Game screen blocked after response of showParentalGate:

### ISSUE THREAD

**Issue by jgonfer** [flooptech/dist-sdk-ios#2]
Hi, I've implemented your SDK and it's working until you close the Parental Control View, or you answer successfully. Then, the Parental Control View disappears but you can't interact with the game screen. It's a little strange, like if a View remains at the top.

I've test it in iOS 7 & iOS 8 devices and happens the same behavior. I'm just using this method:

```objective-c
[[FloopSdkManager sharedInstance] showParentalGate:^(BOOL success) {
            if (success) {
                GameViewController * viewController = (GameViewController *) self.view.window.rootViewController;
                [viewController rateApp];
            }
            
        }];
```

UPDATE: After review my code again, I've seen that was my fault. Everything is working fine ;]

**Comment by sanxfxteam** [comment]
Hi Josep,
Just wanted to check out, is the issue fixed?
Laurent,

**Comment by jgonfer** [comment]
Hi Laurent,
In fact, it wasn't a bug, it was my fault. I forgot to enable touch event handler for buttons when Control Parental View disappears ;) The SDK is working fine in iOS 7 and iOS 8. Very useful SDK!
